#\!/bin/bash

echo "============================================="
echo "  Chrome Dependencies Installation Script"
echo "============================================="
echo ""
echo "This script will install the required dependencies for running Chrome/Chromium with Puppeteer."
echo "You will need sudo access to install these packages."
echo ""
echo "Required packages to install:"
echo "  - libxkbcommon0 (MISSING - causing the current error)"
echo "  - Other Chrome/Chromium dependencies"
echo ""
echo "Run the following command to install all dependencies:"
echo ""
echo "sudo apt-get update && sudo apt-get install -y \\"
echo "  libxkbcommon0 libxkbcommon-x11-0 libnss3 libatk-bridge2.0-0 \\"
echo "  libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxcursor1 \\"
echo "  libxdamage1 libxi6 libxtst6 libappindicator3-1 \\"
echo "  libasound2 libatk1.0-0 libcups2 libdbus-1-3 \\"
echo "  libdrm2 libgbm1 libgtk-3-0 libnspr4 libxrandr2 libxss1"
echo ""
echo "After installing, restart the API with: pnpm dev --filter=api"
echo ""
